### ISSUE TITLE
Cell size issues

### ISSUE THREAD

**Issue by hellerve** [hellerve/cspfuck#3]
As detailed at the end of #2, `cspfuck` is experiencing hiccups when underflowing because it takes an awfully long time to wrap around (with this being integers on the tape). I don’t know whether changing the cell size to 8 bits would be a acceptable solution, or whether we should rather think about making this configurable.

**Comment by rdebath** [comment]
I would say your current implementation, where the integer does NOT wrap, (because of `-ftrapv`) isn't correct for BF. The probable ancestor language [Ρʺ](https://esolangs.org/wiki/P%E2%80%B2%E2%80%B2) specifically defines the language to use a fixed number of symbols and `+` with wrapping to implement `-`. 

Urban Müller's BF implementations used two cell sizes, the old (lost) version used 32bit cells and the known ones use 8bit cells. So IMO both cells sizes are correct (As well as other cells sizes that can reasonably be "machine integers" eg 16, 64, 128, 256 ... )

A simple way of improving the speed of your interpreter, without changing the cell size, would be to start optimising and map the sequence `[-]` to a 'Set-to-zero' instruction. (Though you will need more optimisation than that to run Lost Kingdom).

**Comment by hellerve** [comment]
I just added the `ZERO` bytecode! Thanks for that idea; the program runs much faster now! I will close this issue for now, then.

Thanks again for all your help and suggestions, this has been very helpful in making `cspfuck` more stable!

EDIT: for the record, I also removed `-ftrapv`.
